export const categories = [
  { id: "all", label: "All Agents", icon: "Globe2" },
  { id: "marketing", label: "Marketing", icon: "Megaphone" },
  { id: "finance", label: "Finance", icon: "CircleDollarSign" },
  { id: "hr", label: "HR", icon: "Users" },
  { id: "research", label: "Research", icon: "Microscope" },
  { id: "development", label: "Dev Tools", icon: "Laptop" },
  { id: "data", label: "Data", icon: "BarChart3" },
  { id: "creative", label: "Creative", icon: "Palette" },
  { id: "productivity", label: "Productivity", icon: "Zap" },
  { id: "security", label: "Security", icon: "Lock" }
];

export const agents = [
  {
    id: "69be59ffd2d3e89243881c5f",
    name: "CodeReview Agent",
    creator: "DevTools AI",
    icon: "Laptop",
    category: "development",
    description: "Automated code review agent that analyzes PRs for bugs, security vulnerabilities, and code quality issues.",
    details:
      "CodeReview Agent integrates with your GitHub repos to provide instant, thorough code reviews. It catches bugs, security flaws, performance issues, and style inconsistencies. Supports 15+ languages including Python, JavaScript, Go, and Rust.",
    tags: ["github", "code-review", "security", "devtools"],
    capabilities: ["Bug detection", "Security vulnerability scanning", "Performance analysis", "Code style enforcement", "Automated suggestions"],
    rating: 4.9,
    reviews: 890,
    runs: "120,800",
    price: "$29/mo",
    pricing: "Subscription",
    version: "4.2.0",
    success: "99%",
    latency: "< 15s",
    badge: "Premium Verified",
    output:
      "Code Review Summary\n-------------------\nFiles: 12 | Lines: 847\n\nCritical: 1 (SQL injection in auth.py:45)\nWarning: 3\nSuggestions: 7\n\nOverall: NEEDS REVISION"
  },
  {
    id: "69be59ffd2d3e89243881c63",
    name: "ThreatHunter",
    creator: "CyberShield AI",
    icon: "Lock",
    category: "security",
    description: "Security agent that continuously monitors your infrastructure for threats, vulnerabilities, and anomalous behavior.",
    details:
      "ThreatHunter connects to cloud logs, endpoint telemetry, and SIEM exports to surface active risks before they become incidents.",
    tags: ["monitoring", "threats", "cloud"],
    capabilities: ["Cloud log monitoring", "Anomaly detection", "Risk scoring", "Incident briefs"],
    rating: 4.8,
    reviews: 640,
    runs: "95,600",
    price: "$79/mo",
    pricing: "Subscription",
    version: "3.7.1",
    success: "98%",
    latency: "< 30s",
    badge: "Premium Verified",
    output: "Threat brief: unusual IAM activity detected. Recommended action: rotate keys and restrict source IP ranges."
  },
  {
    id: "69be59ffd2d3e89243881c64",
    name: "CryptoSentinel",
    creator: "QuantChain AI",
    icon: "CircleDollarSign",
    category: "finance",
    description: "AI-powered crypto trading bot with real-time market analysis, risk management, and automated trade execution.",
    details: "CryptoSentinel watches market momentum, liquidity shifts, and portfolio risk to propose disciplined trading actions.",
    tags: ["crypto", "trading", "defi"],
    capabilities: ["Market analysis", "Risk limits", "Trade alerts", "Portfolio summaries"],
    rating: 4.5,
    reviews: 410,
    runs: "89,200",
    price: "$99/mo",
    pricing: "Subscription",
    version: "2.9.4",
    success: "96%",
    latency: "< 10s",
    badge: "Verified",
    output: "BTC trend: neutral-to-bullish. Risk: medium. Suggested allocation change: +2% with tight stop-loss."
  },
  {
    id: "69be59ffd2d3e89243881c61",
    name: "ContentForge",
    creator: "CreativeAI Studio",
    icon: "Palette",
    category: "creative",
    description: "Creative AI agent that generates blog posts, social media content, and marketing copy tailored to your brand voice.",
    details: "ContentForge learns your tone and produces structured content briefs, drafts, and channel-specific variants.",
    tags: ["content", "writing", "seo"],
    capabilities: ["Blog drafting", "SEO briefs", "Social variants", "Brand voice matching"],
    rating: 4.6,
    reviews: 525,
    runs: "67,300",
    price: "$19/mo",
    pricing: "Subscription",
    version: "5.0.2",
    success: "97%",
    latency: "< 20s",
    badge: "Verified",
    output: "Draft package ready: headline options, SEO outline, 900-word article, and three social captions."
  },
  {
    id: "69be59ffd2d3e89243881c65",
    name: "ResearchBot Pro",
    creator: "AcademiaAI",
    icon: "Microscope",
    category: "research",
    description: "Autonomous research agent that finds, analyzes, and synthesizes information from academic papers and the web.",
    details: "ResearchBot Pro compiles citations, compares findings, and generates literature-review style summaries.",
    tags: ["academic", "papers", "literature-review"],
    capabilities: ["Source discovery", "Citation summaries", "Evidence grading", "Research memos"],
    rating: 4.3,
    reviews: 318,
    runs: "52,100",
    price: "Free",
    pricing: "Free",
    version: "1.8.0",
    success: "94%",
    latency: "< 45s",
    badge: "Verified",
    output: "Research memo generated with 14 sources, key disagreements, and recommended next readings."
  },
  {
    id: "69be59ffd2d3e89243881c62",
    name: "MeetingMind",
    creator: "Productiv Labs",
    icon: "Zap",
    category: "productivity",
    description: "Productivity agent that records meetings, generates summaries, extracts action items, and syncs with your task manager.",
    details: "MeetingMind turns meeting transcripts into concise summaries, decisions, owners, and due dates.",
    tags: ["meetings", "transcription", "tasks"],
    capabilities: ["Meeting summaries", "Action extraction", "Calendar sync", "Task creation"],
    rating: 4.7,
    reviews: 455,
    runs: "41,200",
    price: "Free",
    pricing: "Free",
    version: "2.4.6",
    success: "98%",
    latency: "< 25s",
    badge: "Verified",
    output: "Summary ready: three decisions, five action items, two blockers, and owners synced to the project board."
  },
  {
    id: "69be59ffd2d3e89243881c5d",
    name: "TalentScreen AI",
    creator: "HireWise",
    icon: "Users",
    category: "hr",
    description: "Intelligent resume screening agent that evaluates candidates, ranks applications, and generates interview questions.",
    details: "TalentScreen AI compares candidate evidence against role criteria and produces explainable shortlists.",
    tags: ["hiring", "resume", "screening"],
    capabilities: ["Resume scoring", "Candidate ranking", "Bias checks", "Interview prompts"],
    rating: 4.8,
    reviews: 372,
    runs: "34,500",
    price: "$0.5/use",
    pricing: "Pay Per Use",
    version: "3.1.8",
    success: "97%",
    latency: "< 18s",
    badge: "Verified",
    output: "Top candidates ranked with skill evidence, gaps, and suggested interview questions."
  },
  {
    id: "69be59ffd2d3e89243881c66",
    name: "DataPipeline AI",
    creator: "DataFlow Inc",
    icon: "BarChart3",
    category: "data",
    description: "Intelligent ETL agent that automates data extraction, transformation, and loading across multiple sources.",
    details: "DataPipeline AI discovers schemas, proposes transformations, and monitors pipeline health.",
    tags: ["etl", "pipeline", "analytics"],
    capabilities: ["Schema mapping", "Data validation", "Pipeline monitoring", "Alert summaries"],
    rating: 4.4,
    reviews: 280,
    runs: "28,900",
    price: "$1/use",
    pricing: "Pay Per Use",
    version: "2.2.1",
    success: "95%",
    latency: "< 40s",
    badge: "Verified",
    output: "Pipeline plan created: 4 sources, 12 transformations, validation rules, and scheduled health checks."
  },
  {
    id: "69be59ffd2d3e89243881c5b",
    name: "AdGenius Pro",
    creator: "MarketMind Labs",
    icon: "Megaphone",
    category: "marketing",
    description: "Autonomous marketing agent that creates, manages, and optimizes ad campaigns across Google, Meta, and TikTok.",
    details: "AdGenius Pro tests audience segments, generates creative variants, and reallocates budget to top performers.",
    tags: ["advertising", "google-ads", "meta-ads"],
    capabilities: ["Campaign setup", "Budget optimization", "Creative generation", "Performance reporting"],
    rating: 4.7,
    reviews: 198,
    runs: "15,420",
    price: "$49/mo",
    pricing: "Subscription",
    version: "4.0.5",
    success: "96%",
    latency: "< 35s",
    badge: "Verified",
    output: "Campaign optimization complete: shifted 18% budget to best CPA audience and generated five new ad variants."
  }
];
